singleQuote: true
semi: false
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrderParserPlugins:
  - 'typescript'
  - 'decorators-legacy'
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder:
  - '^@(.*)$'
  - '^src(.*)$'
  - '^[./]'
# # Default values (https://prettier.io/docs/en/options)
#   endOfLine: "lf",
#   printWidth: 80,
#   tabWidth: 2,
#   useTabs: false
